app:
  env: compose
log:
  level: debug
  file: /app/logs/app.log
swagger:
  enabled: true
database:
  name: platform
  schema: billing
grpc:
  reflection_enabled: true
cron:
  enabled: true
service_registry:
  allow_insecure: true
